<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20160818023950 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('CREATE TABLE we_news_domain_model_scrapingsource (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, url VARCHAR(2000) NOT NULL, listhtmlselector VARCHAR(255) NOT NULL, detailhtmlselector VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE we_news_domain_model_news (persistence_object_identifier VARCHAR(40) NOT NULL, scrapingsource VARCHAR(40) DEFAULT NULL, title VARCHAR(255) NOT NULL, lead LONGTEXT DEFAULT NULL, body LONGTEXT NOT NULL, author VARCHAR(255) DEFAULT NULL, crdate DATETIME NOT NULL, INDEX IDX_AED593CCCE16A30F (scrapingsource), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE we_news_domain_model_news ADD CONSTRAINT FK_AED593CCCE16A30F FOREIGN KEY (scrapingsource) REFERENCES we_news_domain_model_scrapingsource (persistence_object_identifier)');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE we_news_domain_model_news DROP FOREIGN KEY FK_AED593CCCE16A30F');
        $this->addSql('DROP TABLE we_news_domain_model_scrapingsource');
        $this->addSql('DROP TABLE we_news_domain_model_news');
    }
}