<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20160819014219 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE we_news_domain_model_scrapingsource ADD titlehtmlselector VARCHAR(255) NOT NULL, ADD leadhtmlselector VARCHAR(255) NOT NULL, ADD detailurlhtmlselector VARCHAR(255) NOT NULL, ADD thumbnailhtmlselector VARCHAR(255) NOT NULL, ADD authorhtmlselector VARCHAR(255) NOT NULL, ADD datehtmlselector VARCHAR(255) NOT NULL, ADD bodyhtmlselector VARCHAR(255) NOT NULL, ADD imagehtmlselector VARCHAR(255) NOT NULL');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE we_news_domain_model_scrapingsource DROP titlehtmlselector, DROP leadhtmlselector, DROP detailurlhtmlselector, DROP thumbnailhtmlselector, DROP authorhtmlselector, DROP datehtmlselector, DROP bodyhtmlselector, DROP imagehtmlselector');
    }
}